# Generated by Django 4.1.1 on 2022-09-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_song_delete_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=256, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('digital', models.BooleanField(blank=True, default=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('highResSong', models.FileField(upload_to='highResMusic/')),
                ('song', models.FileField(upload_to='music/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
