# Generated by Django 4.1.1 on 2022-09-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_music_delete_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('request', models.CharField(max_length=500)),
                ('request_id', models.CharField(max_length=100, null=True)),
                ('replied', models.BooleanField(default=False)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
