# Generated by Django 4.1.1 on 2022-09-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customer_hearted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='hearted',
            new_name='favorite',
        ),
    ]
