# Generated by Django 4.1.1 on 2022-09-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_hearted_customer_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='favorite',
        ),
    ]
